apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      file {
        path => "/var/log/*.log"
        start_position => "beginning"
      }
    }
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:message}" }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
      stdout { codec => json }
    }

